# Generated by Django 5.1.4 on 2025-01-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Information',
        ),
    ]
