# Generated by Django 5.1.4 on 2025-01-14 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_information_notice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(
                                      default=None,  # Use None or provide a valid default value
                                           on_delete=django.db.models.deletion.CASCADE,
                          to=settings.AUTH_USER_MODEL
),

        ),
    ]


