# Generated by Django 5.1.4 on 2025-01-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_notice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='user',
        ),
    ]
