# Generated by Django 5.1.4 on 2025-01-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=10)),
                ('user_address', models.TextField()),
                ('user_dob', models.DateField()),
                ('user_profile_pic', models.ImageField(upload_to='UserProfile/ProfilePic/')),
            ],
        ),
    ]
