# Generated by Django 5.1.4 on 2025-01-11 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserAccount',
        ),
    ]
