# Generated by Django 5.1.4 on 2025-01-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_nick_name',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
