# Generated by Django 5.1.4 on 2025-01-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_userprofile_user_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_nick_name',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
