# Generated by Django 5.1.4 on 2025-01-11 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_alter_userprofile_user_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_nick_name',
            field=models.CharField(default='User', max_length=20),
        ),
        migrations.CreateModel(
            name='School_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('class_teacher', models.CharField(max_length=20)),
                ('class_number', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.useraccount')),
            ],
        ),
    ]
