# Generated by Django 5.1.4 on 2025-01-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0007_alter_userprofile_user_nick_name_school_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school_class',
            options={'verbose_name_plural': 'School Class'},
        ),
        migrations.RemoveField(
            model_name='school_class',
            name='student',
        ),
        migrations.AddField(
            model_name='school_class',
            name='student',
            field=models.ManyToManyField(to='UserProfile.useraccount'),
        ),
    ]
