# Generated by Django 5.1.4 on 2025-01-11 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0008_alter_school_class_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_class',
            old_name='student',
            new_name='students',
        ),
    ]
